language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
before_deploy:
  - mkdir -p before-deploy
  - cp compose/* before-deploy/
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp target/*.war before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/spring-maven-webservice.zip
# CodeDeploy는 Jar파일을 인식하지 못하므로 zip파일로 압축한다.

deploy:
  - provider: s3
    access_key_id: AKIA6L54DEAOJJP74GLY
    secret_access_key: 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
    bucket: spring-web-build-travis
    region: ap-northeast-2
    cleanup: true
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider : codedeploy
    access_key_id: AKIA6L54DEAOJJP74GLY
    secret_access_key: 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	
    bucket: spring-web-build-travis
    key: spring-maven-webservice.zip # travis 와 다른게 확장자 제거
    bundle_type: zip
    application: spring-web-codeDeploy
    deployment_group: spring-web-codeDeploy-group
    region: ap-northeast-2
    wait_until_deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - oinia2@naver.com
