version: '3'

services:
  nginx:
    image: oinia2/aws-spring-web:0.94
    deploy:
      replicas: 2
      #placement:
      #  constraints: [node.role != manager]
      restart_policy:
        condition: on-failure
        max_attempts: 80
    ports:
      - 8080:8080            
      - 80:8080
    environment:
      - SERVICE_PORTS=8080
    networks:
      - test
  
networks:
  test:
    external: true
